### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by wolone** [jenkey2011/vuepress-deploy#1]
`
==> Start building \n yarn build
yarn run v1.12.3
warning package.json: No license field
$ vuepress build blog
/bin/sh: vuepress: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

`
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: wolone/blog
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn build
        BUILD_DIR: blog/.vuepress/dist/
`

**Comment by lizhongyue248** [comment]
依赖中添加 `vuepress`， `scripts` 使用 `npx` 可解决

```
  "docs:dev": "npx vuepress dev docs",
  "docs:build": "npx vuepress build docs"
```
