### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by wangdaodao** [jenkey2011/vuepress-deploy#11]
```
Done in 23.51s.
Build success
==> Changing directory to 'docs/.vuepress/dist/' ...
==> Prepare to deploy
Initialized empty Git repository in /github/workspace/docs/.vuepress/dist/.git/
Generating a CNAME file...
==> Starting deploying
error: pathspec 'deploy' did not match any file(s) known to git.
error: pathspec 'from' did not match any file(s) known to git.
error: pathspec 'Github' did not match any file(s) known to git.
error: pathspec 'Actions' did not match any file(s) known to git.
```

action代码没有改过，突然报错。

```
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Const-Team/Document
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist/
```

**Comment by naikyding** [comment]
+1

**Comment by jenkey2011** [comment]
抱歉…… 
目前已恢复，上次更新一个字段问题，先回退了，后续验证后重新提一下

**Comment by jenkey2011** [comment]
搞定了，现在支持自定义提交信息
详情参考文档：https://github.com/jenkey2011/vuepress-deploy/blob/master/README.zh-CN.md#%E5%8F%82%E6%95%B0
例子：https://github.com/jenkey2011/vuepress-deploy-demo/blob/master/.github/workflows/deploy-to-other-repo-custom_branch.yml#L18


Now, support custom commit message~
For more infomation: https://github.com/jenkey2011/vuepress-deploy/blob/master/README.md#parameters
e.g.:https://github.com/jenkey2011/vuepress-deploy-demo/blob/master/.github/workflows/deploy-to-other-repo-custom_branch.yml#L18

**Comment by wangdaodao** [comment]
> 
> 
> 抱歉……
> 目前已恢复，上次更新一个字段问题，先回退了，后续验证后重新提一下

不用抱歉，本来就是开源的东西，没必要抱歉，感谢你对开源做的一切。
