### ISSUE TITLE
update information link

### ISSUE THREAD

**Issue by tianheg** [jenkey2011/vuepress-deploy#13]
**Describe the bug**

> the `more information` need update

I put all information under the `Step-by-Step Guide` so that it seems tidy.

I had commit my modification [jenkey2011/vuepress-deploy/compare/master...tianheg:master](https://github.com/jenkey2011/vuepress-deploy/compare/master...tianheg:master)

**Comment by jenkey2011** [comment]
Thanks @tianheg , the PR #14 has been merged~
