### ISSUE TITLE
fatal: could not read Password for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by hoochanlon** [jenkey2011/vuepress-deploy#17]
**Describe the issue**

**Comment by jenkey2011** [comment]
I just tested it, and everything looks OK. Maybe paste me a link? @hoochanlon

**Comment by jenkey2011** [comment]
抱歉回复晚了，此问题已在`v1.8.1`修复.

Sorry for the late reply, this problem has been fixed in v1.8.1

```yml
uses: jenkey2011/vuepress-deploy@v1.8.1
```
