### ISSUE TITLE
问题：fatal: could not read Password for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by 9527DHX** [jenkey2011/vuepress-deploy#19]
看见前面的iss也有人遇到这样的情况
查看 vuepress-deploy-demo 最近部署失败的Actions原因好像也是这个😺 @jenkey2011

**Comment by jenkey2011** [comment]
抱歉回复晚了，此问题已在`v1.8.1`修复.

Sorry for the late reply, this problem has been fixed in v1.8.1

```yml
uses: jenkey2011/vuepress-deploy@v1.8.1
```
