### ISSUE TITLE
部署又报错，**

### ISSUE THREAD

**Issue by AkarinLiu** [jenkey2011/vuepress-deploy#23]
![image](https://user-images.githubusercontent.com/58081491/132455507-d00b1146-bdee-45da-9a28-3fc97e6e8d29.png)
[log.txt](https://github.com/jenkey2011/vuepress-deploy/files/7126298/log.txt)
https://github.com/LiuDarkShaoYe/liushaoye.top/blob/master/.github/workflows/main.yml

**Comment by jenkey2011** [comment]
```sh
remote: Invalid username or password.
fatal: Authentication failed for '***github.com/LiuDarkShaoYe/***.git/'
```

Seems like the personal access token is incorrect.

看起来你配置的Token不对

**Comment by AkarinLiu** [comment]
![image](https://user-images.githubusercontent.com/58081491/132526133-32989a27-7d74-4c32-9301-7b078b791338.png)
我添加了secrets.TOKEN，怎么会有错？

**Comment by jenkey2011** [comment]
It seems to have been solved. https://github.com/LiuDarkShaoYe/liushaoye.top/actions

**Comment by lmy668** [comment]
> It seems to have been solved. https://github.com/LiuDarkShaoYe/liushaoye.top/actions

the url is invalid, my workflows has the same problem, but i config the secret.
[https://github.com/lmy668/vuepress/actions/runs/5431057816/jobs/9877308839](url)
