### ISSUE TITLE
exec: "/entrypoint.sh": permission denied: unknown.

### ISSUE THREAD

**Issue by pagnkelly** [jenkey2011/vuepress-deploy#24]
https://github.com/mpx-ecology/eslint-plugin-mpx/runs/5720232845?check_suite_focus=true

也许是我这个用户在这个项目中的权限不高？

**Comment by jenkey2011** [comment]
可能生成的ACCESS_TOKEN权限不够，重新生成一个试试
@pagnkelly

**Comment by pagnkelly** [comment]
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/16016300/161040429-fb20fade-5b0d-49ac-af9f-87df3799fa37.png">
查了下说是docker镜像与系统不兼容，可是按照你的docker配置生成的，不知道为撒哈

**Comment by pagnkelly** [comment]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/16016300/161057043-265a6b0d-6919-4119-94f1-48a31513c358.png">
想问下为什么我的二级域名（项目名称）丢了

**Comment by pagnkelly** [comment]
你好像打包进去了，我再看看vuepress吧

**Comment by jenkey2011** [comment]
路径就是纯vuepress问题了哈 @pagnkelly

**Comment by pagnkelly** [comment]
yes, 已经解决了
